site_name: phanulab.github.io
nav:
  - Home: index.md
  - Academics: 
    - "Overview": academic/overview.md
    - "Courses":
      - Discrete Mathematics: docs/academic/courses/mathdisc.md
      - Data Mining Technology: docs/academic/courses/dmtech.md
      - English for Academic and Specific Purposes: docs/academic/courses/easp.md
    - Resouces:
      - name of resource: docs/academic/resources/name-of-resource.md
  - Blog:
    - Blog index by tags: docs/blog/index.md
    - Year 2023:
        - Blog Post Title: docs/blog/2023-mm-dd-blog-post-title.md
#    - Chapters:
#      - "Preface": chapters/Preface.md
#      - "1. Why FAIR training & training materials?": chapters/chapter_01.md
#      - "2. Structure materials for FAIRness": chapters/chapter_02.md
#      - "3. Getting ready to create your materials or reuse": chapters/chapter_03.md
#      - "4. Using metadata to describe training materials": chapters/chapter_04.md
#      - "5. Get a persistent identifier for your training material": chapters/chapter_05.md
#      - "6. Make it accessible": chapters/chapter_06.md
#      - "7. Make it reusable": chapters/chapter_07.md
#      - "8. Licensing": chapters/chapter_08.md
#      - "9. Boosting discoverability": chapters/chapter_09.md
#      - "10. Recognition, acknowledgment, authorship": chapters/chapter_10.md
#    - Keywords list: keywords.md
#    - Miscellaneous:
#     - ""
#

theme:
  name: material
  logo: assets/images/ssrucspxwfav.png
  favicon: assets/images/ssrucspxwfav.ico
  custom_dir: overrides
  features:
    - navigation.tabs

# Repository
repo_name: phanulab.github.io
repo_url: https://github.com/PhanuLab/phanulab.github.io
edit_uri: edit/master/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
