site_name: phanulab.github.io

nav:
 - Home: index.md
 - Courses:
   - Discrete Mathematics: courses/mathdisc.md
   - Data Mining Technology: courses/dmtech.md
   - English for Academic and Specific Purposes: courses/easp.md
 - Lecture Notes:
   - "DMTech-Lecture01": lecture-notes/dmtech-lect01-intro.md
   - "EASP-Lecture01": lecture-notes/easp-lect01-intro.md
   - "MathDisc-Lecture01": lecture-notes/mathdisc-lect01-intro.md
 - FAIR Guide:
     - "Preface": fair-chapters/Preface.md
     - "1. Why FAIR training & training materials?": fair-chapters/chapter_01.md
     - "2. Structure materials for FAIRness": fair-chapters/chapter_02.md
     - "3. Getting ready to create your materials or reuse": fair-chapters/chapter_03.md
     - "4. Using metadata to describe training materials": fair-chapters/chapter_04.md
     - "5. Get a persistent identifier for your training material": fair-chapters/chapter_05.md
     - "6. Make it accessible": fair-chapters/chapter_06.md
     - "7. Make it reusable": fair-chapters/chapter_07.md
     - "8. Licensing": fair-chapters/chapter_08.md
     - "9. Boosting discoverability": fair-chapters/chapter_09.md
     - "10. Recognition, acknowledgment, authorship": fair-chapters/chapter_10.md
 - Blog Posts:
   - Posts index by tags: posts/index.md
   - Year 2023:
     - Sample Blog Post Title: posts/2023-01-21-sample-blog-post-title.md
 - Keywords list: keywords.md
  
theme:
  name: material
  logo: assets/images/ssrucspxwfav.png
  favicon: assets/images/ssrucspxwfav.ico
  custom_dir: overrides
  features:
    - navigation.tabs

# Repository
repo_name: phanulab.github.io
repo_url: https://github.com/PhanuLab/phanulab.github.io
edit_uri: edit/master/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
