# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / MkDocs
nav:
- Home: index.md
- Overview: overview.md
#- Install MkDocs: install.md
- Install MkDocs: install.md
- MkDocs Version Differences: mkdocs-versions.md
- New Project: new-project.md
- Configuration: config.md
- Edit Content: edit.md
- Material Theme:  material-theme.md
- Deploy Website: deploy.md
- Use Site: use-site.md
- Troubleshooting: troubleshooting.md
- Resources: resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme.
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-mkdocs
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Open Water Foundation Learn MkDocs
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.ico'
# ------------------------------------------------
# The following controls how URLs are created:
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
